"""auto_sync_20260316_205242

Revision ID: 5c6ad77680db
Revises: adda8cb62fb5
Create Date: 2026-03-16 20:52:43.963902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c6ad77680db'
down_revision: Union[str, Sequence[str], None] = 'adda8cb62fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inference', 'prompt',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('inference', 'negative_prompt',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inference', 'negative_prompt',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('inference', 'prompt',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
