"""auto_sync_20260315_193039

Revision ID: 5e1c5bbb17b0
Revises: 
Create Date: 2026-03-15 19:30:40.105724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1c5bbb17b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_configuration_id'), 'app_configuration', ['id'], unique=False)
    op.create_index(op.f('ix_app_configuration_key'), 'app_configuration', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_configuration_key'), table_name='app_configuration')
    op.drop_index(op.f('ix_app_configuration_id'), table_name='app_configuration')
    op.drop_table('app_configuration')
    # ### end Alembic commands ###
