"""auto_sync_20260316_215941

Revision ID: 6468d606e7f8
Revises: f9f022ebfc99
Create Date: 2026-03-16 21:59:42.378339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6468d606e7f8'
down_revision: Union[str, Sequence[str], None] = 'f9f022ebfc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inference', 'seed',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inference', 'seed',
               existing_type=sa.String(length=255),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
    # ### end Alembic commands ###
