"""auto_sync_20260316_140052

Revision ID: 8483c9dfb660
Revises: 5e1c5bbb17b0
Create Date: 2026-03-16 14:00:54.350887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8483c9dfb660'
down_revision: Union[str, Sequence[str], None] = '5e1c5bbb17b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_blob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_blob_id'), 'image_blob', ['id'], unique=False)
    op.create_index(op.f('ix_image_blob_name'), 'image_blob', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_blob_name'), table_name='image_blob')
    op.drop_index(op.f('ix_image_blob_id'), table_name='image_blob')
    op.drop_table('image_blob')
    # ### end Alembic commands ###
