"""auto_sync_20260316_201901

Revision ID: adda8cb62fb5
Revises: bcc0dea9bfd4
Create Date: 2026-03-16 20:19:02.050590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'adda8cb62fb5'
down_revision: Union[str, Sequence[str], None] = 'bcc0dea9bfd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference', sa.Column('blob_id', sa.String(length=255), nullable=True))
    op.add_column('inference', sa.Column('seed', sa.Integer(), nullable=True))
    op.add_column('inference', sa.Column('scheduler', sa.String(length=255), nullable=True))
    op.alter_column('inference', 'prompt',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('inference', 'num_inference_steps',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('inference', 'guidance_scale',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.create_unique_constraint(None, 'inference', ['blob_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inference', type_='unique')
    op.alter_column('inference', 'guidance_scale',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('inference', 'num_inference_steps',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('inference', 'prompt',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('inference', 'scheduler')
    op.drop_column('inference', 'seed')
    op.drop_column('inference', 'blob_id')
    # ### end Alembic commands ###
