"""auto_sync_20260316_155252

Revision ID: bcc0dea9bfd4
Revises: 8483c9dfb660
Create Date: 2026-03-16 15:52:53.115845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bcc0dea9bfd4'
down_revision: Union[str, Sequence[str], None] = '8483c9dfb660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.String(length=255), nullable=False),
    sa.Column('negative_prompt', sa.String(length=255), nullable=True),
    sa.Column('num_inference_steps', sa.Integer(), nullable=False),
    sa.Column('guidance_scale', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_id'), 'inference', ['id'], unique=False)
    op.create_index(op.f('ix_inference_status'), 'inference', ['status'], unique=False)
    op.drop_index(op.f('ix_image_blob_id'), table_name='image_blob')
    op.drop_index(op.f('ix_image_blob_name'), table_name='image_blob')
    op.drop_table('image_blob')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_blob',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('data', mysql.VARCHAR(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_image_blob_name'), 'image_blob', ['name'], unique=True)
    op.create_index(op.f('ix_image_blob_id'), 'image_blob', ['id'], unique=False)
    op.drop_index(op.f('ix_inference_status'), table_name='inference')
    op.drop_index(op.f('ix_inference_id'), table_name='inference')
    op.drop_table('inference')
    # ### end Alembic commands ###
